/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felszerelesraktarnyilvantartoapp;

import static felszerelesraktarnyilvantartoapp.FelszerelesraktarNyilvantartoApp.hideButtons;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author oldman96
 */
public class Beallitasok extends javax.swing.JFrame {

    /**
     * Creates new form FelszerelesekWindow
     */
    public Beallitasok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kijelentkezesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        felhKezelesBtn = new javax.swing.JButton();
        beallitasokLabel = new javax.swing.JLabel();
        nevjegyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Beállítások");

        kijelentkezesBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kijelentkezesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_32px.png"))); // NOI18N
        kijelentkezesBtn.setText("Kijelentkezés");
        kijelentkezesBtn.setBorderPainted(false);
        kijelentkezesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kijelentkezesBtn.setFocusPainted(false);
        kijelentkezesBtn.setFocusable(false);
        kijelentkezesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kijelentkezesBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Version 1.0");

        felhKezelesBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        felhKezelesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_management_32px.png"))); // NOI18N
        felhKezelesBtn.setText("<html><center>Felhasználók<br>kezelése</center></html>");
        felhKezelesBtn.setBorderPainted(false);
        felhKezelesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        felhKezelesBtn.setFocusPainted(false);
        felhKezelesBtn.setFocusable(false);
        felhKezelesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                felhKezelesBtnActionPerformed(evt);
            }
        });

        beallitasokLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        beallitasokLabel.setText("Beállítások");

        nevjegyBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nevjegyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_about_32px.png"))); // NOI18N
        nevjegyBtn.setText("Névjegy");
        nevjegyBtn.setBorderPainted(false);
        nevjegyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nevjegyBtn.setFocusPainted(false);
        nevjegyBtn.setFocusable(false);
        nevjegyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevjegyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kijelentkezesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(beallitasokLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nevjegyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(felhKezelesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(beallitasokLabel)
                .addGap(31, 31, 31)
                .addComponent(felhKezelesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(nevjegyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kijelentkezesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kijelentkezesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kijelentkezesBtnActionPerformed
        ImageIcon kerdesIcon = new ImageIcon(getClass().getResource("/icons/icons8_help_48px.png"));
        Object[] options = {"Igen", "Mégse"};
            int n = JOptionPane.showOptionDialog(this, "Biztosan kijelentkezik?", "Kijelentkezés",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, kerdesIcon, options, options[1]);
            if(n==JOptionPane.YES_OPTION){  
                //FelszerelesraktarNyilvantartoApp.hideButtons();
                this.dispose();
                java.awt.EventQueue.invokeLater(() -> {
                    hideButtons();
                    Belepes B = new Belepes();
                            B.setVisible(true);
                });
            }
    }//GEN-LAST:event_kijelentkezesBtnActionPerformed

    private void felhKezelesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_felhKezelesBtnActionPerformed
        ImageIcon hibaIcon = new ImageIcon(getClass().getResource("/icons/icons8_cancel_48px.png"));
        if(!FelszerelesraktarNyilvantartoApp.getBelepettFelhasznalo().equals("admin")){
            JOptionPane.showMessageDialog(this, "Belépés megtagadva.\nAdmin jogosultság szükséges!","Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
        }else{
            java.awt.EventQueue.invokeLater(() -> {
                new Felhasznalok().setVisible(true);
            });
        }
    }//GEN-LAST:event_felhKezelesBtnActionPerformed

    private void nevjegyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevjegyBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new Nevjegy().setVisible(true);
        });
    }//GEN-LAST:event_nevjegyBtnActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FelszerelesekWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beallitasokLabel;
    private static javax.swing.JButton felhKezelesBtn;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JButton kijelentkezesBtn;
    private static javax.swing.JButton nevjegyBtn;
    // End of variables declaration//GEN-END:variables
}
