/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felszerelesraktarnyilvantartoapp;

import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author oldman96
 */
public class Belepes extends javax.swing.JFrame {

    private static String fnev = "";
    private static String jelszo = "";
    /**
     * Creates new form Belepes
     */
    public Belepes() {
        initComponents();
    }
    
    public static String getFnev() {
        return fnev;
    }

    public static String getJelszo() {
        return jelszo;
    }
    
    private void belepesCheck(){
        
            ImageIcon sikerIcon = new ImageIcon(getClass().getResource("/icons/icons8_ok_48px.png"));
            ImageIcon hibaIcon = new ImageIcon(getClass().getResource("/icons/icons8_cancel_48px.png"));
            ImageIcon kerdesIcon = new ImageIcon(getClass().getResource("/icons/icons8_help_48px.png"));
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/raktardb","root","projektlabor");  
            Statement stmt=con.createStatement(); 
            ResultSet AdatLekeroQuery=stmt.executeQuery("select COUNT(*) from felhasznaloktbl WHERE Felhasznalonev='"+fnevTextField.getText()+"';");
            String eredm ="1";
            while(AdatLekeroQuery.next()){
                eredm = AdatLekeroQuery.getString(1);
            }
            
            String jelszoFromDB = "";
            AdatLekeroQuery=stmt.executeQuery("select Jelszo from felhasznaloktbl WHERE Felhasznalonev='"+fnevTextField.getText()+"';");
            while(AdatLekeroQuery.next()){
                jelszoFromDB = AdatLekeroQuery.getString(1);
            }
           if(eredm.equals("0")){
               JOptionPane.showMessageDialog(this, "Nem létezik ilyen felhasználó.","Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
           } else if(!FelszerelesraktarNyilvantartoApp.passwordMD5(jelszoTextField.getText()).equals(jelszoFromDB)){
               JOptionPane.showMessageDialog(this, "Érvénytelen jelszó","Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
           }else{
               fnev = fnevTextField.getText();
               JOptionPane.showMessageDialog(this, "Sikeres belépés.","Belépve!", JOptionPane.INFORMATION_MESSAGE, sikerIcon);
                FelszerelesraktarNyilvantartoApp.unHideButtons();
                FelszerelesraktarNyilvantartoApp.setFelhasznaloLabelText(fnev);
                FelszerelesraktarNyilvantartoApp.setBelepettFelhasznalo(fnev);
                this.dispose();
           }
           
           con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Létrehozás sikertelen.\n" + e,"Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
        }
        
//        if(fnevTextField.getText().equals(fnev) && jelszoTextField.getText().equals(jelszo)){
//            JOptionPane.showMessageDialog(this, "Sikeres belépés.","Belépve!", JOptionPane.INFORMATION_MESSAGE, sikerIcon);
//            FelszerelesraktarNyilvantartoApp.unHideButtons();
//            FelszerelesraktarNyilvantartoApp.setFelhasznaloLabelText(fnev);
//            FelszerelesraktarNyilvantartoApp.setBelepettFelhasznalo(fnev);
//            this.dispose();
//        } else{
//            JOptionPane.showMessageDialog(this, "Hibás felhasználó/jelszó.","Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
//        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bejelentkezesLabel = new javax.swing.JLabel();
        fnevTextField = new javax.swing.JTextField();
        jelszoTextField = new javax.swing.JPasswordField();
        belepesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bejelentkezés");
        setAlwaysOnTop(true);

        bejelentkezesLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bejelentkezesLabel.setText("Bejelentkezés");

        jelszoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jelszoTextFieldActionPerformed(evt);
            }
        });
        jelszoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jelszoTextFieldKeyPressed(evt);
            }
        });

        belepesBtn.setText("OK");
        belepesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belepesBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Felhasználó:");

        jLabel2.setText("Jelszó:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jelszoTextField)
                    .addComponent(fnevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(bejelentkezesLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(belepesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(bejelentkezesLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jelszoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(belepesBtn)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jelszoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jelszoTextFieldActionPerformed
        
    }//GEN-LAST:event_jelszoTextFieldActionPerformed

    private void belepesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belepesBtnActionPerformed
        belepesCheck();
    }//GEN-LAST:event_belepesBtnActionPerformed

    private void jelszoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jelszoTextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){ //ENTER leutesre is belep
            belepesCheck();
        }
    }//GEN-LAST:event_jelszoTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bejelentkezesLabel;
    private javax.swing.JButton belepesBtn;
    private javax.swing.JTextField fnevTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jelszoTextField;
    // End of variables declaration//GEN-END:variables
}
