/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felszerelesraktarnyilvantartoapp;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author oldman96
 */
public class Felhasznalok extends javax.swing.JFrame {
    private static FelhasznalokTableModel ftm;
    private int filterByColumn;
    private final ImageIcon sikerIcon = new ImageIcon(getClass().getResource("/icons/icons8_ok_48px.png"));
    private final ImageIcon hibaIcon = new ImageIcon(getClass().getResource("/icons/icons8_cancel_48px.png"));
    private final ImageIcon kerdesIcon = new ImageIcon(getClass().getResource("/icons/icons8_help_48px.png"));
    

    /**
     * Creates new form FelszerelesekWindow
     */
    public Felhasznalok() {
        initComponents();
        
        ftm = new FelhasznalokTableModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
    
        felhasznalokTable.setModel(ftm);
        felhasznalokTable.getColumnModel().getColumn(0).setMinWidth(250);
        felhasznalokTable.getTableHeader().setFont(new java.awt.Font("Tahoma", 1, 14));
        felhasznalokTable.getTableHeader().setOpaque(false);
        felhasznalokTable.getTableHeader().setBackground(new Color(196, 196, 196));

    }
    
    
    
    public static void setTm(FelhasznalokTableModel _ftm){
        ftm=_ftm;
    }
    
    public static void refreshTable(){
        ftm.fireTableDataChanged();
        felhasznalokTable.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        felhasznalokTable = new javax.swing.JTable();
        hozzaadasBtn = new javax.swing.JButton();
        megseBtn1 = new javax.swing.JButton();
        eltavolitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Felhasználók");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        felhasznalokTable.setAutoCreateRowSorter(true);
        felhasznalokTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        felhasznalokTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Gyártó (típus)", "Kategória", "Évjárat", "Állapot", "Raktár", "Beszerzési Ár", "Beszerzés helye", "Azonosító"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        felhasznalokTable.setIntercellSpacing(new java.awt.Dimension(8, 5));
        felhasznalokTable.setRowHeight(60);
        jScrollPane1.setViewportView(felhasznalokTable);

        hozzaadasBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hozzaadasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-list-32.png"))); // NOI18N
        hozzaadasBtn.setText("<html><center>Új<br> <center>felhasználó</html>");
        hozzaadasBtn.setBorderPainted(false);
        hozzaadasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hozzaadasBtn.setFocusPainted(false);
        hozzaadasBtn.setFocusable(false);
        hozzaadasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadasBtnActionPerformed(evt);
            }
        });

        megseBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        megseBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_32px_2.png"))); // NOI18N
        megseBtn1.setText("Mégse");
        megseBtn1.setBorderPainted(false);
        megseBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        megseBtn1.setFocusPainted(false);
        megseBtn1.setFocusable(false);
        megseBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                megseBtn1ActionPerformed(evt);
            }
        });

        eltavolitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eltavolitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-list-32.png"))); // NOI18N
        eltavolitBtn.setText("Eltávolít");
        eltavolitBtn.setBorderPainted(false);
        eltavolitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eltavolitBtn.setFocusPainted(false);
        eltavolitBtn.setFocusable(false);
        eltavolitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eltavolitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hozzaadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eltavolitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(megseBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(hozzaadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(eltavolitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(megseBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hozzaadasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadasBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new UjFelhasznalo().setVisible(true);
        });
        
    }//GEN-LAST:event_hozzaadasBtnActionPerformed

    private void megseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_megseBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_megseBtn1ActionPerformed

    private void eltavolitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eltavolitBtnActionPerformed
        if(felhasznalokTable.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Nincs kijelölve felhasználó.","Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
            }
            else if(felhasznalokTable.getSelectedRowCount() > 1){
                JOptionPane.showMessageDialog(this, "Egyszerre csak egy felhasználót lehet törölni.","Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
            }else if(ftm.getValueAt(felhasznalokTable.getSelectedRow()).equals("admin")){
                JOptionPane.showMessageDialog(this, "Admin felhasználót nem lehet törölni.","Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
            }else{
                Object[] options = {"Igen", "Mégse"};
                int n = JOptionPane.showOptionDialog(this, "Biztosan törölni szeretné a felhasználót?", "Biztos benne?",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, kerdesIcon, options, options[1]);
                if(n==JOptionPane.YES_OPTION){  
                    String felh = ftm.getValueAt(felhasznalokTable.getSelectedRow());
                    try{
                        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/raktardb","root","projektlabor");  
                        Statement stmt=con.createStatement(); 
                        stmt.executeUpdate("delete from felhasznaloktbl where Felhasznalonev like '"+ felh +"';");
                        //Felszerelesek.setTm(new TableModel());
                        FelhasznalokTableModel.deleteValueAt(felhasznalokTable.getSelectedRow());
                        this.refreshTable();
                        JOptionPane.showMessageDialog(this, "Felhasználó eltávolítva.","Sikeres törlés!", JOptionPane.INFORMATION_MESSAGE, sikerIcon);
                        con.close();

                    } catch(Exception e){
                        JOptionPane.showMessageDialog(this, "Törlés sikertelen\n" + e,"Hiba!", JOptionPane.INFORMATION_MESSAGE, hibaIcon);
                    } 
                }                
        }
    }//GEN-LAST:event_eltavolitBtnActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FelszerelesekWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eltavolitBtn;
    private static javax.swing.JTable felhasznalokTable;
    private javax.swing.JButton hozzaadasBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton megseBtn1;
    // End of variables declaration//GEN-END:variables
}
