/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felszerelesraktarnyilvantartoapp;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author oldman96
 */
public class FelszerelesraktarNyilvantartoApp extends javax.swing.JFrame {

    private JButton b1;
    private JLabel l1;
    private static String belepettFelhasznalo;
    

    /**
     * Creates new form FelszerelesraktarNyilvantartoApp
     */
    public FelszerelesraktarNyilvantartoApp() {
        initComponents();
        Tarolo tar = new Tarolo();
        tar.Beolvas();
        setLayout(new BorderLayout());
        JLabel background=new JLabel(new ImageIcon("src\\background\\rental3.jpg"));
        add(background);
        background.setLayout(new FlowLayout());
        pack(); // automatically size the window to fit its components
        setLocationRelativeTo(null); // center this window on the screen
        setDefaultCloseOperation(EXIT_ON_CLOSE); // when this window is closed, exit this application
        
        
        java.awt.EventQueue.invokeLater(() -> {
            hideButtons();
            Belepes B = new Belepes();
            B.setVisible(true);
        });
        
    }
    
    public static void hideButtons(){
        beallBtn.setVisible(false);
        beolvasBtn.setVisible(false);
        felszListBtn.setVisible(false);
        infoBtn.setVisible(false);
        kiadasBtn.setVisible(false);
        kolcsonzesekBtn.setVisible(false);
        ujBeszBtn.setVisible(false);
        infoBtn.setVisible(false);
        bejelentkezveLabel.setVisible(false);
        felhasznaloLabel.setVisible(false);
    }
    
    public static void unHideButtons(){
        beallBtn.setVisible(true);
        beolvasBtn.setVisible(true);
        felszListBtn.setVisible(true);
        infoBtn.setVisible(true);
        kiadasBtn.setVisible(true);
        kolcsonzesekBtn.setVisible(true);
        ujBeszBtn.setVisible(true);
        infoBtn.setVisible(true);
        bejelentkezveLabel.setVisible(true);
        felhasznaloLabel.setVisible(true);
    }
    
    public static void setFelhasznaloLabelText(String s){
        felhasznaloLabel.setText(s);
    }
    
    public static String getBelepettFelhasznalo() {
        return belepettFelhasznalo;
    }

    public static void setBelepettFelhasznalo(String belepettFelhasznalo) {
        FelszerelesraktarNyilvantartoApp.belepettFelhasznalo = belepettFelhasznalo;
    }
    
    public static String passwordMD5(String password) throws NoSuchAlgorithmException{
        String generatedPassword = null;
               MessageDigest md = MessageDigest.getInstance("MD5");
               md.update(password.getBytes());
               byte[] bytes = md.digest();
               StringBuilder sb = new StringBuilder();
                for(int i=0; i< bytes.length ;i++)
                {
                    sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
                }
                //Get complete hashed password in hex format
                generatedPassword = sb.toString();
        return generatedPassword;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoBtn = new javax.swing.JButton();
        beolvasBtn = new javax.swing.JButton();
        felszListBtn = new javax.swing.JButton();
        ujBeszBtn = new javax.swing.JButton();
        kiadasBtn = new javax.swing.JButton();
        kolcsonzesekBtn = new javax.swing.JButton();
        beallBtn = new javax.swing.JButton();
        bejelentkezveLabel = new javax.swing.JLabel();
        felhasznaloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Felszerelésraktár nyilvántartó rendszer");
        setPreferredSize(new java.awt.Dimension(1000, 700));

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-info-24.png"))); // NOI18N
        infoBtn.setBorderPainted(false);
        infoBtn.setContentAreaFilled(false);
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.setFocusPainted(false);
        infoBtn.setFocusable(false);
        infoBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-info-28.png"))); // NOI18N
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        beolvasBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beolvasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-beolvas-32.png"))); // NOI18N
        beolvasBtn.setText("Beolvasás");
        beolvasBtn.setBorderPainted(false);
        beolvasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beolvasBtn.setFocusPainted(false);
        beolvasBtn.setFocusable(false);
        beolvasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beolvasBtnActionPerformed(evt);
            }
        });

        felszListBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        felszListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-playlist-32.png"))); // NOI18N
        felszListBtn.setText("Felszerelések");
        felszListBtn.setBorderPainted(false);
        felszListBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        felszListBtn.setFocusPainted(false);
        felszListBtn.setFocusable(false);
        felszListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                felszListBtnActionPerformed(evt);
            }
        });

        ujBeszBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ujBeszBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-list-32.png"))); // NOI18N
        ujBeszBtn.setText("Új beszerzés");
        ujBeszBtn.setBorderPainted(false);
        ujBeszBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ujBeszBtn.setFocusPainted(false);
        ujBeszBtn.setFocusable(false);
        ujBeszBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujBeszBtnActionPerformed(evt);
            }
        });

        kiadasBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kiadasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_manual_page_rotation_32px.png"))); // NOI18N
        kiadasBtn.setText("Kiadás");
        kiadasBtn.setBorderPainted(false);
        kiadasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kiadasBtn.setFocusPainted(false);
        kiadasBtn.setFocusable(false);
        kiadasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiadasBtnActionPerformed(evt);
            }
        });

        kolcsonzesekBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kolcsonzesekBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_tiles_32px.png"))); // NOI18N
        kolcsonzesekBtn.setText("Kölcsönzések");
        kolcsonzesekBtn.setBorderPainted(false);
        kolcsonzesekBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kolcsonzesekBtn.setFocusPainted(false);
        kolcsonzesekBtn.setFocusable(false);
        kolcsonzesekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolcsonzesekBtnActionPerformed(evt);
            }
        });

        beallBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        beallBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-settings-32.png"))); // NOI18N
        beallBtn.setText("Beállítások");
        beallBtn.setBorderPainted(false);
        beallBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beallBtn.setFocusPainted(false);
        beallBtn.setFocusable(false);
        beallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beallBtnActionPerformed(evt);
            }
        });

        bejelentkezveLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bejelentkezveLabel.setText("Bejelentkezve:");

        felhasznaloLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(beolvasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(felszListBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ujBeszBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kiadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kolcsonzesekBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bejelentkezveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(felhasznaloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bejelentkezveLabel)
                        .addComponent(felhasznaloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 572, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beolvasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(felszListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ujBeszBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kiadasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolcsonzesekBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new Nevjegy().setVisible(true);
        });
    }//GEN-LAST:event_infoBtnActionPerformed

    private void beolvasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beolvasBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            WebcamBeolvas WB = new WebcamBeolvas();
            WB.setVisible(true);
        });
    }//GEN-LAST:event_beolvasBtnActionPerformed

    private void felszListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_felszListBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new Felszerelesek().setVisible(true);
        });
    }//GEN-LAST:event_felszListBtnActionPerformed

    private void ujBeszBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujBeszBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new UjBeszerzes().setVisible(true);
        });
    }//GEN-LAST:event_ujBeszBtnActionPerformed

    private void kiadasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiadasBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new Kiadas().setVisible(true);
        });
    }//GEN-LAST:event_kiadasBtnActionPerformed

    private void kolcsonzesekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolcsonzesekBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new Kolcsonzesek().setVisible(true);
        });
    }//GEN-LAST:event_kolcsonzesekBtnActionPerformed

    private void beallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beallBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new Beallitasok().setVisible(true);
        });
    }//GEN-LAST:event_beallBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
              javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FelszerelesraktarNyilvantartoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FelszerelesraktarNyilvantartoApp().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton beallBtn;
    private static javax.swing.JLabel bejelentkezveLabel;
    private static javax.swing.JButton beolvasBtn;
    private static javax.swing.JLabel felhasznaloLabel;
    private static javax.swing.JButton felszListBtn;
    private static javax.swing.JButton infoBtn;
    private static javax.swing.JButton kiadasBtn;
    private static javax.swing.JButton kolcsonzesekBtn;
    private static javax.swing.JButton ujBeszBtn;
    // End of variables declaration//GEN-END:variables
}
