/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felszerelesraktarnyilvantartoapp;

import java.security.SecureRandom;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import javax.swing.JFrame;
import java.util.Random;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import java.util.concurrent.TimeUnit;
import java.security.SecureRandom;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import javax.swing.JFrame;
import java.util.Random;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import java. util. Calendar;
import java.util.Date;




/**
 *
 * @author oldman96
 */
public class Kiadas extends javax.swing.JFrame {

    /**
     * Creates new form FelszerelesekWindow
     */
    
    
    private ArrayList<String> telephelyek = new ArrayList<String>();
   
    public static String WebcamEredmeny="";
    
    private WebcamKiadas webcam =  new WebcamKiadas();
    
    public Kiadas() {
        ComboboxFeltoltes();
        initComponents();
        this.KolcsKezdeteTextfield.setText(DateNow());
        webcam.setVisible(false);

    }
    
    private String DateNow(){
        SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//dd/MM/yyyy
        Date now = new Date();
        String strDate = sdfDate.format(now);
        return strDate;
    }
    
    
    private void ComboboxFeltoltes(){
        
        try{
            if(!telephelyek.isEmpty())
            {
                telephelyek.clear();
            }
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/raktardb","root","projektlabor");  
            Statement stmt=con.createStatement(); 
            
            ResultSet AdatLekeroQuery=stmt.executeQuery("select telephelyektbl.Telephely from telephelyektbl");
            while(AdatLekeroQuery.next())  // ha van még sor --> sor beolvasása
            { 
                telephelyek.add(AdatLekeroQuery.getString(1));
                //System.out.println(AdatLekeroQuery.getString(1));
            }
            
             con.close();
        }
             catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        } 
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QRkodLabel = new javax.swing.JLabel();
        QRkodTextfield = new javax.swing.JTextField();
        KolcsKezdeteLabel = new javax.swing.JLabel();
        KolcsKezdeteTextfield = new javax.swing.JTextField();
        KiadasHelyLabel = new javax.swing.JLabel();
        KolcsHelyeCombobox = new javax.swing.JComboBox<>();
        NevLabel = new javax.swing.JLabel();
        NevTextfield = new javax.swing.JTextField();
        KiadasButton = new javax.swing.JButton();
        TelefonLabel = new javax.swing.JLabel();
        WebcamBeolvasButton = new javax.swing.JButton();
        TelefonTextfield = new javax.swing.JTextField();
        MegseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Felszerelés selejtezése");

        QRkodLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QRkodLabel.setText("QR kód:");

        QRkodTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        KolcsKezdeteLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        KolcsKezdeteLabel.setText("Kölcsönzés kezdete: ");

        KolcsKezdeteTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        KiadasHelyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        KiadasHelyLabel.setText("Kiadás helye:");

        KolcsHelyeCombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KolcsHelyeCombobox.setModel(new javax.swing.DefaultComboBoxModel<String>(telephelyek.toArray(new String[0])));

        NevLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NevLabel.setText("Név:");

        NevTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        KiadasButton.setText("Kiadás");
        KiadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KiadasButtonActionPerformed(evt);
            }
        });

        TelefonLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TelefonLabel.setText("Telefonszám:");

        WebcamBeolvasButton.setText("Beolvas");
        WebcamBeolvasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebcamBeolvasButtonActionPerformed(evt);
            }
        });

        TelefonTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MegseButton.setText("Mégse");
        MegseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MegseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QRkodLabel)
                    .addComponent(KolcsKezdeteLabel)
                    .addComponent(NevLabel)
                    .addComponent(TelefonLabel)
                    .addComponent(KiadasHelyLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KolcsKezdeteTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QRkodTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(WebcamBeolvasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(KolcsHelyeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TelefonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NevTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KiadasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(MegseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NevLabel)
                    .addComponent(NevTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonLabel)
                    .addComponent(TelefonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KiadasHelyLabel)
                    .addComponent(KolcsHelyeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KolcsKezdeteLabel)
                    .addComponent(KolcsKezdeteTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QRkodLabel)
                    .addComponent(QRkodTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebcamBeolvasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MegseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KiadasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KiadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KiadasButtonActionPerformed
        // TODO add your handling code here:
        //System.out.println(GyartoTextfield.getText());
        
        String eredm ="0";
        String raktarban="0";
        
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/raktardb","root","projektlabor");  
            Statement stmt=con.createStatement(); 
            
            try{
                ResultSet AdatLekeroQuery=stmt.executeQuery("select COUNT(*) from raktartbl WHERE QRKod='"+this.QRkodTextfield.getText()+"';");
            
                while(AdatLekeroQuery.next()){
                    eredm = AdatLekeroQuery.getString(1);
                }
            
                    try{
                        AdatLekeroQuery=stmt.executeQuery("select COUNT(*) from kolcsonzesektbl WHERE QRKod='"+this.QRkodTextfield.getText()+"' and KolcsDateTo like '0%' ;");

                        while(AdatLekeroQuery.next()){
                        raktarban = AdatLekeroQuery.getString(1);
                        }
                    }
                    catch(Exception e)
                        {
                        JOptionPane.showMessageDialog(null,e);
                        }  
            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null,e);
            }  
            
            if(eredm.equals("1") && raktarban.equals("0")){
                try{
                    stmt.executeUpdate("INSERT INTO `kolcsonzesektbl` (`QRkod`, `SzNev`, `Telefon`, `KolcsDateFrom`, `KolcsDateTo`, `TelepFrom`, `TelepTo`, `ID`) "
                    + "VALUES ("
                    + "'"+this.QRkodTextfield.getText()+"', "
                    + "'"+this.NevTextfield.getText()+"', "
                    + "'"+this.TelefonTextfield.getText()+"', "
                    + "'"+this.KolcsKezdeteTextfield.getText()+"', "
                    + "'0000-00-00 00:00:00', "
                    + "'"+this.KolcsHelyeCombobox.getSelectedItem()+"', "
                    + "'', "
                    + "NULL);");
            
                    con.close();
                    JOptionPane.showMessageDialog(this, "Sikeres kiadás!");
                    this.dispose();
                    }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                } 
            }
            else{
                JOptionPane.showMessageDialog(null,"A QR kód nem található a rendszerben vagy kölcsönzés alatt áll!\n");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }  
    }//GEN-LAST:event_KiadasButtonActionPerformed

    private void WebcamBeolvasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebcamBeolvasButtonActionPerformed
        // TODO add your handling code here:
        
           webcam.setVisible(true);
           
    }//GEN-LAST:event_WebcamBeolvasButtonActionPerformed

    private void MegseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MegseButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_MegseButtonActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FelszerelesekWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KiadasButton;
    private javax.swing.JLabel KiadasHelyLabel;
    private javax.swing.JComboBox<String> KolcsHelyeCombobox;
    private javax.swing.JLabel KolcsKezdeteLabel;
    private javax.swing.JTextField KolcsKezdeteTextfield;
    private javax.swing.JButton MegseButton;
    private javax.swing.JLabel NevLabel;
    private javax.swing.JTextField NevTextfield;
    private javax.swing.JLabel QRkodLabel;
    private javax.swing.JTextField QRkodTextfield;
    private javax.swing.JLabel TelefonLabel;
    private javax.swing.JTextField TelefonTextfield;
    private javax.swing.JButton WebcamBeolvasButton;
    // End of variables declaration//GEN-END:variables
}
