/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felszerelesraktarnyilvantartoapp;

import java.security.SecureRandom;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import javax.swing.JFrame;
import java.util.Random;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import java.util.concurrent.TimeUnit;
import java.security.SecureRandom;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import javax.swing.JFrame;
import java.util.Random;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import java. util. Calendar;
import java.util.Date;


/**
 *
 * @author Daniel
 */
public class Leadás extends javax.swing.JFrame {

    /**
     * Creates new form Leadás
     */
    private ArrayList<String> telephelyek = new ArrayList<String>();
    final private Kolcsonzes k;
    private String WebcamEredmeny="";
    private String eredm ="0";
    private WebcamKiadas webcam =  new WebcamKiadas();
    
    
    
    public Leadás(Kolcsonzes _k) {
        k=_k;
        ComboboxFeltoltes();
        initComponents();
        this.NevTextfield.setText(k.getNev());
        this.TelefonTextfield.setText(k.getTelefon());
        this.KolcsVegeTextfield.setText(DateNow());
        this.QRkodTextfield.setText(k.getQRkod());
        webcam.setVisible(false);
    }        
        
    
    private String DateNow(){
        SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//dd/MM/yyyy
        Date now = new Date();
        String strDate = sdfDate.format(now);
        return strDate;
    }
    
    
    private void ComboboxFeltoltes(){
        
        try{
            if(!telephelyek.isEmpty())
            {
                telephelyek.clear();
            }
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/raktardb","root","projektlabor");  
            Statement stmt=con.createStatement(); 
            
            ResultSet AdatLekeroQuery=stmt.executeQuery("select telephelyektbl.Telephely from telephelyektbl");
            while(AdatLekeroQuery.next())  // ha van még sor --> sor beolvasása
            { 
                telephelyek.add(AdatLekeroQuery.getString(1));
                //System.out.println(AdatLekeroQuery.getString(1));
            }
            
             con.close();
        }
             catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WebcamBeolvasButton = new javax.swing.JButton();
        QRkodLabel = new javax.swing.JLabel();
        TelefonTextfield = new javax.swing.JTextField();
        QRkodTextfield = new javax.swing.JTextField();
        MegseButton = new javax.swing.JButton();
        KolcsVegLabel = new javax.swing.JLabel();
        KolcsVegeTextfield = new javax.swing.JTextField();
        LeadasHelyLabel = new javax.swing.JLabel();
        KolcsLeadHelyeCombobox = new javax.swing.JComboBox<>();
        NevLabel = new javax.swing.JLabel();
        NevTextfield = new javax.swing.JTextField();
        LeadasButton = new javax.swing.JButton();
        TelefonLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WebcamBeolvasButton.setText("Beolvas");
        WebcamBeolvasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WebcamBeolvasButtonActionPerformed(evt);
            }
        });

        QRkodLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        QRkodLabel.setText("QR kód:");

        TelefonTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TelefonTextfield.setEnabled(false);

        QRkodTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        QRkodTextfield.setEnabled(false);

        MegseButton.setText("Mégse");
        MegseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MegseButtonActionPerformed(evt);
            }
        });

        KolcsVegLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        KolcsVegLabel.setText("Kölcsönzés vége: ");

        KolcsVegeTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LeadasHelyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LeadasHelyLabel.setText("Leadás helye:");

        KolcsLeadHelyeCombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KolcsLeadHelyeCombobox.setModel(new javax.swing.DefaultComboBoxModel<String>(telephelyek.toArray(new String[0])));

        NevLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NevLabel.setText("Név:");

        NevTextfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NevTextfield.setEnabled(false);

        LeadasButton.setText("Leadás");
        LeadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeadasButtonActionPerformed(evt);
            }
        });

        TelefonLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TelefonLabel.setText("Telefonszám:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QRkodLabel)
                    .addComponent(KolcsVegLabel)
                    .addComponent(NevLabel)
                    .addComponent(TelefonLabel)
                    .addComponent(LeadasHelyLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KolcsVegeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QRkodTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(WebcamBeolvasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(KolcsLeadHelyeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NevTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LeadasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(MegseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NevLabel)
                    .addComponent(NevTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonLabel)
                    .addComponent(TelefonTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeadasHelyLabel)
                    .addComponent(KolcsLeadHelyeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KolcsVegLabel)
                    .addComponent(KolcsVegeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QRkodLabel)
                    .addComponent(QRkodTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebcamBeolvasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MegseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeadasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WebcamBeolvasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WebcamBeolvasButtonActionPerformed
        // TODO add your handling code here:

        webcam.setVisible(true);

    }//GEN-LAST:event_WebcamBeolvasButtonActionPerformed

    private void MegseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MegseButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_MegseButtonActionPerformed

    private void LeadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeadasButtonActionPerformed
        // TODO add your handling code here:
        //System.out.println(GyartoTextfield.getText());
        
        eredm ="0";

        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/raktardb","root","projektlabor");
            Statement stmt=con.createStatement();

            try{
                ResultSet AdatLekeroQuery=stmt.executeQuery("select COUNT(*) from kolcsonzesektbl WHERE QRKod='"+k.getQRkod()+"' and KolcsDateTo like '0%' ;");                                                    
                while(AdatLekeroQuery.next()){
                    eredm = AdatLekeroQuery.getString(1);
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }

            if(eredm.equals("1")){
                try{
                    stmt.executeUpdate("UPDATE kolcsonzesektbl SET KolcsDateTo='"+this.KolcsVegeTextfield.getText()+"' , TelepTo='"+this.KolcsLeadHelyeCombobox.getSelectedItem()+"' "
                        + " where SzNev like '"+k.getNev()+"' and KolcsDateFrom like '"+k.getKolcskezd()+"' ;" );

                    con.close();
                    JOptionPane.showMessageDialog(this, "Sikeres leadás!");
                    this.dispose();
                    Kolcsonzesek.setTm(new KolcsonzesekTableModel());
                    Kolcsonzesek.refreshTable();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Az eszköz nem áll kölcsönzés alatt!\n");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_LeadasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leadás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leadás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leadás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leadás.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leadás().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> KolcsLeadHelyeCombobox;
    private javax.swing.JLabel KolcsVegLabel;
    private javax.swing.JTextField KolcsVegeTextfield;
    private javax.swing.JButton LeadasButton;
    private javax.swing.JLabel LeadasHelyLabel;
    private javax.swing.JButton MegseButton;
    private javax.swing.JLabel NevLabel;
    private javax.swing.JTextField NevTextfield;
    private javax.swing.JLabel QRkodLabel;
    private javax.swing.JTextField QRkodTextfield;
    private javax.swing.JLabel TelefonLabel;
    private javax.swing.JTextField TelefonTextfield;
    private javax.swing.JButton WebcamBeolvasButton;
    // End of variables declaration//GEN-END:variables
}
