/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felszerelesraktarnyilvantartoapp;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.SecureRandom;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import javax.swing.JFrame;
import java.util.Random;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author oldman96
 */
public class Reszletek extends javax.swing.JFrame {
    
    final private Felszereles f;
    private static final int QR_size_px = 300;
    
    /**
     * Creates new form FelszerelesekWindow
     * @param _f
     * @throws com.google.zxing.WriterException
     * @throws java.io.IOException
     */
    
    public Reszletek(Felszereles _f) throws WriterException, IOException {
        f = _f;
        initComponents();
        assignValues();
        setFormatCommands();
        //this.repaint();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MegnevezesLabel = new javax.swing.JLabel();
        GyartoLabel = new javax.swing.JLabel();
        GyartoTextfield = new javax.swing.JTextField();
        TipusLabel = new javax.swing.JLabel();
        TipusTextfield = new javax.swing.JTextField();
        AdatokLabel = new javax.swing.JLabel();
        KategoriaLabel = new javax.swing.JLabel();
        AlkategoriaLabel = new javax.swing.JLabel();
        EvjaratLabel = new javax.swing.JLabel();
        AllapotLabel = new javax.swing.JLabel();
        BeszerzArLabel = new javax.swing.JLabel();
        BeszerzArTextfield = new javax.swing.JTextField();
        BeszerzHelyLabel = new javax.swing.JLabel();
        BeszerzHelyTextfield = new javax.swing.JTextField();
        SnLabel = new javax.swing.JLabel();
        SnTextfield = new javax.swing.JTextField();
        RaktarhelyLabel = new javax.swing.JLabel();
        RaktariAzonositoLabel = new javax.swing.JLabel();
        RaktariAzonositoTextfield = new javax.swing.JTextField();
        KategoriaTextfield = new javax.swing.JTextField();
        AlkategoriaTextfield = new javax.swing.JTextField();
        megseBtn1 = new javax.swing.JButton();
        EvjaratTextfield = new javax.swing.JTextField();
        AllapotTextfield = new javax.swing.JTextField();
        RaktarhelyTextfield = new javax.swing.JTextField();
        QRImgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Termék adatlap");

        MegnevezesLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MegnevezesLabel.setText("Megnevezés:");

        GyartoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GyartoLabel.setText("Gyártó:");

        GyartoTextfield.setEditable(false);
        GyartoTextfield.setBackground(new java.awt.Color(255, 255, 255));
        GyartoTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        TipusLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TipusLabel.setText("Típus:");

        TipusTextfield.setEditable(false);
        TipusTextfield.setBackground(new java.awt.Color(255, 255, 255));
        TipusTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        AdatokLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AdatokLabel.setText("Adatok:");

        KategoriaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        KategoriaLabel.setText("Kategória:");

        AlkategoriaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AlkategoriaLabel.setText("Alkategória:");

        EvjaratLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EvjaratLabel.setText("Évjárat:");

        AllapotLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AllapotLabel.setText("Állapot:");

        BeszerzArLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BeszerzArLabel.setText("Beszerzési ár:");

        BeszerzArTextfield.setEditable(false);
        BeszerzArTextfield.setBackground(new java.awt.Color(255, 255, 255));
        BeszerzArTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        BeszerzHelyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BeszerzHelyLabel.setText("Beszerzés helye:");

        BeszerzHelyTextfield.setEditable(false);
        BeszerzHelyTextfield.setBackground(new java.awt.Color(255, 255, 255));
        BeszerzHelyTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        SnLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SnLabel.setText("S/N:");

        SnTextfield.setEditable(false);
        SnTextfield.setBackground(new java.awt.Color(255, 255, 255));
        SnTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        RaktarhelyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RaktarhelyLabel.setText("Raktárhely:");

        RaktariAzonositoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RaktariAzonositoLabel.setText("Raktári azonosító:");

        RaktariAzonositoTextfield.setEditable(false);
        RaktariAzonositoTextfield.setBackground(new java.awt.Color(255, 255, 255));
        RaktariAzonositoTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        KategoriaTextfield.setEditable(false);
        KategoriaTextfield.setBackground(new java.awt.Color(255, 255, 255));
        KategoriaTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        AlkategoriaTextfield.setEditable(false);
        AlkategoriaTextfield.setBackground(new java.awt.Color(255, 255, 255));
        AlkategoriaTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        megseBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        megseBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_32px_2.png"))); // NOI18N
        megseBtn1.setText("Mégse");
        megseBtn1.setBorderPainted(false);
        megseBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        megseBtn1.setFocusPainted(false);
        megseBtn1.setFocusable(false);
        megseBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                megseBtn1ActionPerformed(evt);
            }
        });

        EvjaratTextfield.setEditable(false);
        EvjaratTextfield.setBackground(new java.awt.Color(255, 255, 255));
        EvjaratTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        AllapotTextfield.setEditable(false);
        AllapotTextfield.setBackground(new java.awt.Color(255, 255, 255));
        AllapotTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        RaktarhelyTextfield.setEditable(false);
        RaktarhelyTextfield.setBackground(new java.awt.Color(255, 255, 255));
        RaktarhelyTextfield.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AllapotLabel)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(KategoriaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(EvjaratLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(GyartoLabel)
                                        .addGap(35, 35, 35)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(KategoriaTextfield)
                                            .addComponent(GyartoTextfield))
                                        .addGap(111, 111, 111)
                                        .addComponent(TipusLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TipusTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EvjaratTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AllapotTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(SnLabel))
                                            .addComponent(AlkategoriaLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SnTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                            .addComponent(AlkategoriaTextfield))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(408, 408, 408))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(RaktarhelyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RaktarhelyTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BeszerzArLabel)
                                            .addComponent(BeszerzHelyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BeszerzArTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BeszerzHelyTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(408, 408, 408))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RaktariAzonositoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RaktariAzonositoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(QRImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(megseBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MegnevezesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdatokLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(MegnevezesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GyartoLabel)
                            .addComponent(GyartoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipusLabel)
                            .addComponent(TipusTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(AdatokLabel)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AlkategoriaLabel)
                            .addComponent(KategoriaTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlkategoriaTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KategoriaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EvjaratLabel)
                            .addComponent(EvjaratTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AllapotLabel)
                            .addComponent(SnLabel)
                            .addComponent(SnTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AllapotTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(QRImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeszerzArTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeszerzArLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeszerzHelyTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeszerzHelyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaktarhelyLabel)
                    .addComponent(RaktariAzonositoLabel)
                    .addComponent(RaktariAzonositoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RaktarhelyTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(megseBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setFormatCommands(){
        BeszerzArTextfield.setHorizontalAlignment(JTextField.CENTER);
        EvjaratTextfield.setHorizontalAlignment(JTextField.RIGHT);
        AllapotTextfield.setHorizontalAlignment(JTextField.RIGHT);
        RaktarhelyTextfield.setHorizontalAlignment(JTextField.CENTER);
        RaktariAzonositoTextfield.setHorizontalAlignment(JTextField.CENTER);
        SnTextfield.setHorizontalAlignment(JTextField.CENTER);
        BeszerzHelyTextfield.setHorizontalAlignment(JTextField.CENTER);
    }
    
    private void assignValues() throws WriterException, IOException{
        GyartoTextfield.setText(f.getGyarto());
        TipusTextfield.setText(f.getTipus());
        KategoriaTextfield.setText(f.getKategoria());
        AlkategoriaTextfield.setText(f.getAlkategoria());
        AllapotTextfield.setText(f.getAllapot());
        EvjaratTextfield.setText(f.getEvjarat());
        SnTextfield.setText(f.getGyariszam());
        BeszerzArTextfield.setText(reverseString(reverseString(f.getBeszerzesiAr()).replaceAll("...(?!$)", "$0 ")) + " Ft"); // ar string harmas tagolasa jobbrol
        BeszerzHelyTextfield.setText(f.getBeszerzesiHely());
        RaktarhelyTextfield.setText(f.getTelephely());
        RaktariAzonositoTextfield.setText(f.getQRKod());
        ImageIcon image = new ImageIcon(getQRCodeImage(f.getQRKod(), QR_size_px, QR_size_px));
        QRImgLabel.setIcon(image);
        
    }
    
    private BufferedImage getQRCodeImage(String text, int width, int height) throws WriterException, IOException {
        QRCodeWriter qrCodeWriter = new QRCodeWriter();
        BitMatrix bitMatrix = qrCodeWriter.encode(text, BarcodeFormat.QR_CODE, width, height);
        ByteArrayOutputStream pngOutputStream = new ByteArrayOutputStream();
        BufferedImage img = MatrixToImageWriter.toBufferedImage(bitMatrix);
        return img;
    }
    
    public static String reverseString(String str){  
        StringBuilder sb=new StringBuilder(str);  
        sb.reverse();  
        return sb.toString();  
    }  
    
    private void megseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_megseBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_megseBtn1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FelszerelesekWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FelszerelesekWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdatokLabel;
    private javax.swing.JLabel AlkategoriaLabel;
    private javax.swing.JTextField AlkategoriaTextfield;
    private javax.swing.JLabel AllapotLabel;
    private javax.swing.JTextField AllapotTextfield;
    private javax.swing.JLabel BeszerzArLabel;
    private javax.swing.JTextField BeszerzArTextfield;
    private javax.swing.JLabel BeszerzHelyLabel;
    private javax.swing.JTextField BeszerzHelyTextfield;
    private javax.swing.JLabel EvjaratLabel;
    private javax.swing.JTextField EvjaratTextfield;
    private javax.swing.JLabel GyartoLabel;
    private javax.swing.JTextField GyartoTextfield;
    private javax.swing.JLabel KategoriaLabel;
    private javax.swing.JTextField KategoriaTextfield;
    private javax.swing.JLabel MegnevezesLabel;
    private javax.swing.JLabel QRImgLabel;
    private javax.swing.JLabel RaktarhelyLabel;
    private javax.swing.JTextField RaktarhelyTextfield;
    private javax.swing.JLabel RaktariAzonositoLabel;
    private javax.swing.JTextField RaktariAzonositoTextfield;
    private javax.swing.JLabel SnLabel;
    private javax.swing.JTextField SnTextfield;
    private javax.swing.JLabel TipusLabel;
    private javax.swing.JTextField TipusTextfield;
    private javax.swing.JButton megseBtn1;
    // End of variables declaration//GEN-END:variables
}
