/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package testgui_dec17;

import static java.lang.Integer.parseInt;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import static testgui_dec17.NewJFrame.p1;
import static testgui_dec17.NewJFrame.p3;
import static testgui_dec17.NewJFrame.p4;
import static testgui_dec17.NewJFrame.tar;

/**
 *
 * @author Dániel
 */
public class Kosar extends javax.swing.JPanel {
    String Kivalaszt;
    
    private NewJFx frameRend = new NewJFx();
    /** Creates new form Kosar */
    public Kosar() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        Rendel = new javax.swing.JButton();
        Vegosszeg = new javax.swing.JLabel();
        Torles = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(850, 600));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Végösszeg: ");

        Rendel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Rendel.setText("Tovább a rendeléshez");
        Rendel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RendelActionPerformed(evt);
            }
        });

        Torles.setText("Törlés");
        Torles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TorlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Torles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Vegosszeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(Rendel)))
                        .addGap(0, 482, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Torles)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vegosszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Rendel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RendelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RendelActionPerformed
        frameRend.setVisible(true);
        
    }//GEN-LAST:event_RendelActionPerformed

    private void TorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorlesActionPerformed
        
        
        //String[] LineArray = jList1.getSelectedValue().split(" /");
        //Kivalaszt=LineArray[0];
        
        if(p1.KSRlist.get(0).equals("A kosár üres"))
            {  
            }
        else{
            p1.KSRlist.remove(jList1.getSelectedIndex());
            DefaultListModel<String> kosarModel = new DefaultListModel<>();
            int vego=0;
            for(int k=0;k<p1.KSRlist.size();k++){
                kosarModel.addElement(tar.termekTomb[parseInt(p1.KSRlist.get(k))].ID + 
                        " / " + tar.termekTomb[parseInt(p1.KSRlist.get(k))].nev + 
                        " / " + tar.termekTomb[parseInt(p1.KSRlist.get(k))].kategoria + 
                        " / " + tar.termekTomb[parseInt(p1.KSRlist.get(k))].ar + 
                        " FT");
                vego=vego+(tar.termekTomb[parseInt(p1.KSRlist.get(k))].ar);
            }
            this.jList1.setModel(kosarModel);

            this.Vegosszeg.setText(String.valueOf(vego));
        }
        
        
        
             // TODO add your handling code here:
    }//GEN-LAST:event_TorlesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Rendel;
    private javax.swing.JButton Torles;
    public javax.swing.JLabel Vegosszeg;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JList<String> jList1;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
